### ISSUE TITLE
IndexError in update_user().

### ISSUE THREAD

**Issue by rodrigovalle** [richardmin97/PaintTheWorld#26]
Might be a client side issue with sending incorrect data but we should still be sanitizing input.

Stack trace:
```python
File "/home/ubuntu/PaintTheWorld/Server/painttheworld/app.py", line 47, in post
  args['lat'])
File "/home/ubuntu/PaintTheWorld/Server/painttheworld/game.py", line 135, in update_user
  self.grid[gridloc] = constants.Team.findTeam(id)
IndexError: index -1159925 is out of bounds for axis 0 with size 101
```

**Comment by richardmin97** [comment]
I thought there was bound checking provided via the check_grid_range function.
Will check.

**Comment by richardmin97** [comment]
Make sure to pull -- that is an old version of the code. Line 135 is actually the precise check that fixes this case now.
